trigger: none # No CI builds, only PR builds

jobs:
  # GetReleaseVersion
  - template: platforms/templates/get-release-version.yml

  # Import OS-specific build definitions
  - template: platforms/windows.yml
  - template: platforms/macos.yml
  - template: platforms/linux.yml
